services:
  - type: cron
    name: notion-map-sync
    schedule: "*/30 * * * *"  # 每 30 分鐘執行一次
    envVars:
      - key: NOTION_TOKEN
        sync: false
      - key: DATABASE_ID
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
    run: python main.py
